apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: rustfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustfs
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: rustfs
          image: rustfs/rustfs:latest
          resources: {}
          env: []
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rustfs

---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
spec:
  ports:
    - name: s3
      port: 9000
    - name: console
      port: 9001
  selector:
    app.kubernetes.io/name: rustfs
  type: ClusterIP
---

