apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data
  namespace: emqx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emqx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: emqx
    spec:
      containers:
        - name: emqx
          image: emqx:5.4.1
          env:
            - name: EMQX_NODE__NAME
              value: emqx@127.0.0.1
          volumeMounts:
            - mountPath: /opt/emqx/data/
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: emqx-data
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: emqx
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqtts
    - port: 8083
      name: ws
    - port: 8084
      name: wss
    - port: 18083
      name: ui
