apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data
  namespace: emqx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx:5.4.1
          env:
            - name: EMQX_NAME
              value: emqx
            - name: EMQX_HOST
              value: "192.168.1.2"
          volumeMounts:
            - mountPath: /opt/emqx/data/
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: emqx-data
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
spec:
  type: ClusterIP
  selector:
    app: emqx
  ports:

---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
spec:
  type: ClusterIP
  selector:
    app: emqx
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqtts
    - port: 8083
      name: ws
    - port: 8084
      name: wss
    - port: 18083
      name: ui
