apiVersion: apps/v1
kind: Deployment
metadata:
  name: privoxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privoxy
  template:
    metadata:
      labels:
        app: privoxy
    spec:
      containers:
        - name: privoxy
          image: vimagick/privoxy
          env:
          volumeMounts:
            - mountPath: /etc/privoxy/config
              name: privoxy-config
              subPath: config
      volumes:
        - name: privoxy-config
          configMap:
            name: privoxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: privoxy-config
data:
  config: |

    user-manual /usr/share/doc/privoxy/user-manual
    confdir /etc/privoxy
    logdir /var/log/privoxy
    actionsfile match-all.action # Actions that are applied to all sites and maybe overruled later on.
    actionsfile default.action   # Main actions file
    actionsfile user.action      # User customizations
    filterfile default.filter
    filterfile user.filter      # User customizations
    logfile logfile
    listen-address :8118
    toggle  1
    enable-remote-toggle  0
    enable-remote-http-toggle  0
    enable-edit-actions 0
    enforce-blocks 0
    buffer-limit 4096
    enable-proxy-authentication-forwarding 0
    forwarded-connect-retries  0
    accept-intercepted-requests 0
    allow-cgi-request-crunching 0
    split-large-forms 0
    keep-alive-timeout 5
    tolerate-pipelining 1
    socket-timeout 300
    max-client-connections 512
---
apiVersion: v1
kind: Service
metadata:
  name: privoxy
spec:
  type: ClusterIP
  selector:
    app: privoxy
  ports:
    - port: 8118
