apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.15.4
          volumeMounts:
            - mountPath: /qdrant/storage
              name: qdrant
      volumes:
        - name: qdrant
          persistentVolumeClaim:
            claimName: qdrant
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
spec:
  ports:
    - port: 6333
  selector:
    app: qdrant
  type: ClusterIP
---

