apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:5.12.0
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: NodePort
  selector:
    app: neo4j
  ports:
    - port: 7474
      nodePort: 30474
      name: neo4j-http
    - port: 7687
      nodePort: 30687
      name: neo4j-bolt
