apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-express
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://172.16.98.151

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  ports:
    - port: 8081
  selector:
    app.kubernetes.io/name: mongo-express
  type: ClusterIP
