apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: mongo
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      nodePort: 30217
  selector:
    app: mongo
  type: NodePort
