apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heimdall
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heimdall
    spec:
      volumes:
        - name: heimdall
          persistentVolumeClaim:
            claimName: heimdall
      containers:
        - name: heimdall
          image: lscr.io/linuxserver/heimdall:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - mountPath: /config
              name: heimdall
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: heimdall
  type: ClusterIP
