apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase
          env:
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
          volumeMounts:
            - mountPath: /metabase-data
              name: metabase
      volumes:
        - name: metabase
          persistentVolumeClaim:
            claimName: metabase
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  type: ClusterIP
  selector:
    app: metabase
  ports:
    - port: 3000
