apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
spec:
  ports:
    - port: 4822
  selector:
    app: guacd
  type: ClusterIP
