apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guacamole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole
          env:
            - name: POSTGRESQL_HOSTNAME
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRESQL_DATABASE
              value: postgres
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: guacpassword
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"

---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: guacamole
  type: ClusterIP
