apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: sameersbn/redmine:4.1.1-9
          ports:
            - containerPort: 80
          env:
            - name: DB_ADAPTER
              value: postgresql
            - name: DB_USER
              value: redmine
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: redmine
            - name: DB_PASS
              value: mypassword
          volumeMounts:
            - mountPath: /home/redmine/data
              name: redmine-files
      volumes:
        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  ports:
    - port: 80
      nodePort: 30300
  selector:
    app: redmine
  type: NodePort
