apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.23.5
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - name: http
      port: 3000
      nodePort: 30300
    - name: ssh
      port: 22
      nodePort: 30022
  selector:
    app: gitea
  type: NodePort
