apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:latest
          volumeMounts:
            - mountPath: /config
              name: homeassistant
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  ports:
    - port: 8123
      nodePort: 30123
  selector:
    app: homeassistant
  type: NodePort
