apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cron
    spec:
      containers:
        - image: nextcloud:30.0.2
          name: cron
          command:
            - /cron.sh
          envFrom:
            - secretRef:
                name: environment
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
      restartPolicy: Always
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
