apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:30.0.2
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
          envFrom:
            - secretRef:
                name: environment
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  ports:
    - port: 80
  selector:
    app: nextcloud
  type: ClusterIP
