apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-configs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-icons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:0.15.3
          env:
            - name: PASSWORD
              value: mypassword
          volumeMounts:
            - mountPath: /data
              name: homarr-data
            - mountPath: /app/data/configs
              name: homarr-configs
            - mountPath: /app/public/icons
              name: homarr-icons
      volumes:
        - name: homarr-configs
          persistentVolumeClaim:
            claimName: homarr-configs
        - name: homarr-icons
          persistentVolumeClaim:
            claimName: homarr-icons
        - name: homarr-data
          persistentVolumeClaim:
            claimName: homarr-data
---
apiVersion: v1
kind: Service
metadata:
  name: homarr
spec:
  ports:
    - port: 7575
  selector:
    app.kubernetes.io/name: homarr
  type: ClusterIP
