
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: zadam/trilium:0.60.4
          env:
            - name: TRILIUM_PORT
              value: "8080"
          volumeMounts:
            - mountPath: /home/node/trilium-data
              name: trilium
      volumes:
        - name: trilium
          persistentVolumeClaim:
            claimName: trilium
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trilium
  name: trilium
spec:
  ports:
    - port: 8080
      port: 30808
  selector:
    app: trilium
  type: NodePort
