apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trilium
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trilium
    spec:
      containers:
        - name: trilium
          image: zadam/trilium
          volumeMounts:
            - mountPath: /home/node/trilium-data
              name: trilium
      volumes:
        - name: trilium
          persistentVolumeClaim:
            claimName: trilium
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: trilium
  name: trilium
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: trilium
  type: ClusterIP
