apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
    spec:
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:release
          env:
            - name: UPLOAD_LOCATION
              value: ./library
          envFrom:
            - secretRef:
                name: env
          volumeMounts:
            - mountPath: /usr/app/data
              name: immich
          resources: {}
      volumes:
        - name: immich
          persistentVolumeClaim:
            claimName: immich
---
apiVersion: v1
kind: Service
metadata:
  name: immich
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: immich
  ports:
    - port: 2283
