apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adminer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: adminer
  type: ClusterIP
