apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: run
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lib
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: headscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headscale
    spec:
      containers:
        - name: headscale
          image: docker.io/headscale/headscale:latest
          command:
            - headscale
          args:
            - serve
          resources: {}
          env: []
          volumeMounts:
            - mountPath: /var/lib/headscale
              name: lib
            - mountPath: /var/run/headscale
              name: run
            - mountPath: /etc/headscale/config.yaml
              name: config
              subPath: config.yaml

      volumes:
        - name: lib
          persistentVolumeClaim:
            claimName: lib
        - name: run
          persistentVolumeClaim:
            claimName: run
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: headscale
spec:
  ports:
    - name: headscale
      port: 8080
  selector:
    app.kubernetes.io/name: headscale
  type: ClusterIP
