apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
    spec:
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: YOUR_PASSWORD_HERE
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: wordpress
  type: ClusterIP
