apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypiserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pypiserver
  template:
    metadata:
      labels:
        app: pypiserver
    spec:
      containers:
        - name: pypiserver
          image: pypiserver/pypiserver:v2.4.0
          args: ["run", "-a", ".", "-P", "."]
          volumeMounts:
            - mountPath: /data/packages
              name: packages
      volumes:
        - name: packages
          persistentVolumeClaim:
            claimName: pypiserver
---
apiVersion: v1
kind: Service
metadata:
  name: pypiserver
spec:
  type: NodePort
  selector:
    app: pypiserver
  ports:
    - port: 8080
      nodePort: 30808
