---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      volumes:
        - name: node-red
          persistentVolumeClaim:
            claimName: node-red
      containers:
        - name: node-red
          image: nodered/node-red
          volumeMounts:
            - mountPath: /data
              name: node-red
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  ports:
    - port: 1880
  selector:
    app: node-red
  type: ClusterIP
