apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
    spec:
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable

          env:
            - name: OPENCV_FFMPEG_CAPTURE_OPTIONS # Forces RTSP over TCP
              value: rtsp_transport;tcp

          volumeMounts:
            - mountPath: /config/
              name: config
            - name: media
              mountPath: /media/frigate
            - name: shm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  ports:
    - port: 8971 # 5000 for non-autnenticating proxy
  selector:
    app.kubernetes.io/name: frigate
  type: ClusterIP
---
