apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syncthing
    spec:
      containers:
        - name: syncthing
          image: syncthing/syncthing
          env:
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
          volumeMounts:
            - mountPath: /var/syncthing
              name: syncthing-config
            - mountPath: /var/syncthing/Sync
              name: syncthing-data
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-data
          persistentVolumeClaim:
            claimName: syncthing-data
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  ports:
    - name: ui
      port: 8384
      protocol: TCP
      targetPort: 8384
    - name: tcp-file-transfer
      port: 22000
      protocol: TCP
      targetPort: 22000
    - name: quic-file-transfer
      port: 22000
      protocol: UDP
      targetPort: 22000
    - name: discovery
      port: 21027
      protocol: UDP
      targetPort: 21027
  selector:
    app.kubernetes.io/name: syncthing
  type: ClusterIP
