# TODO: should be a secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
  namespace: garage
data:
  garage.toml: |

    # Generated following https://garagehq.deuxfleurs.fr/documentation/quick-start/

    metadata_dir = "/mnt/meta"
    data_dir = "/mnt/data"
    db_engine = "sqlite" # Or "lmdb"

    replication_factor = 1

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "127.0.0.1:3901"
    rpc_secret = "1bf2edfc6808068c734e65c1189e0010650b3e8f37602b327ba223bbb823630d"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.localhost"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.localhost"
    index = "index.html"

    [k2v_api]
    api_bind_addr = "[::]:3904"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "q+4+WgR8CQ3e6rD/H0qo8+Zac/n8fTD7xoJ2hjxpZa4="
    metrics_token = "+zwltFcZWoSk11bPgkeZNc0WSo48SnQlsJsQVsPAaKI="
