apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-webui
  template:
    metadata:
      labels:
        app: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:latest
          env:
            - name: API_BASE_URL
              value: http://garage:3903
            - name: S3_ENDPOINT_URL
              value: http://garage:3900
          volumeMounts:
            - mountPath: /etc/garage.toml
              name: configuration
              subPath: garage.toml
      volumes:
        - name: configuration
          configMap:
            name: configuration
---
apiVersion: v1
kind: Service
metadata:
  name: garage-webui
spec:
  ports:
    - port: 3909
      nodePort: 30909
  selector:
    app: garage-webui
  type: NodePort
