apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
        - name: photoprism
          image: photoprism/photoprism
          env:
            - name: PHOTOPRISM_ADMIN_USER
              value: admin
            - name: PHOTOPRISM_ADMIN_PASSWORD
              value: photoprism
            - name: PHOTOPRISM_AUTH_MODE
              value: password
            - name: PHOTOPRISM_SITE_URL
              value: https://photoprism.home.maximemoreillon.com
            # DB
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_DATABASE_SERVER
              value: mariadb:3306
            - name: PHOTOPRISM_DATABASE_NAME
              value: photoprism
            - name: PHOTOPRISM_DATABASE_USER
              value: photoprism
            - name: PHOTOPRISM_DATABASE_PASSWORD
              value: photoprism
          volumeMounts:
            - mountPath: /photoprism/storage
              name: photoprism-storage
            - mountPath: /photoprism/originals
              name: photoprism-originals
      volumes:
        - name: photoprism-storage
          persistentVolumeClaim:
            claimName: photoprism-storage
        - name: photoprism-originals
          persistentVolumeClaim:
            claimName: photoprism-originals
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
spec:
  type: NodePort
  selector:
    app: photoprism
  ports:
    - port: 2342
      nodePort: 30342
