apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nocodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nocodb
    spec:
      containers:
        - name: nocodb
          image: nocodb/nocodb
          env:
            - name: NC_DB
              value: pg://postgres:5432?u=nocodb&p=nocodb&d=nocodb
            - name: NC_AUTH_JWT_SECRET
              value: keyboardcat
          volumeMounts:
            - mountPath: /usr/app/data
              name: nocodb
      volumes:
        - name: nocodb
          persistentVolumeClaim:
            claimName: nocodb
---
apiVersion: v1
kind: Service
metadata:
  name: nocodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nocodb
  ports:
    - port: 8080
